In [16]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# `tf.nn.conv2d` requires the input be 4D (batch_size, height, width, depth)
# (1, 4, 4, 1)
x = np.array([
    [0, 1, 0.5, 10],
    [2, 2.5, 1, -8],
    [4, 0, 5, 6],
    [15, 1, 2, 3]], dtype=np.float32).reshape((1, 4, 4, 1))
X = tf.constant(x)

# convolution layer
Setup the strides, padding and filter weight/bias such that
the output shape is (1, 2, 2, 3).

In [15]:
def conv2d(input):
    # Filter (weights and bias)
    # The shape of the filter weight is (height, width, input_depth, output_depth)
    # The shape of the filter bias is (output_depth,)
    # TODO: Define the filter weights `F_W` and filter bias `F_b`.
    # NOTE: Remember to wrap them in `tf.Variable`, they are trainable parameters after all.
    F_W = tf.Variable(tf.truncated_normal((2, 2, 1, 3)))
    F_b = tf.Variable(tf.zeros(3))
    # TODO: Set the stride for each dimension (batch_size, height, width, depth)
    strides = [1, 2, 2, 1]
    # TODO: set the padding, either 'VALID' or 'SAME'.
    padding = 'VALID'
    # `tf.nn.conv2d` does not include the bias computation so we have to add it ourselves after.
    return tf.nn.conv2d(input, F_W, strides, padding) + F_b

conv_layer = conv2d(X)
with tf.Session() as sess:
    sess.run(tf. global_variables_initializer())
    conv_out = sess.run(conv_layer)
    
print(conv_out.shape)
print(conv_out)

(1, 2, 2, 3)
[[[[ -1.41279829  -1.86773181   1.59950197]
   [ -8.51319981   8.15742493   0.9950856 ]]

  [[ 12.81463528  -0.42467928   1.60912609]
   [ -2.51165819   1.92294216  -1.8303144 ]]]]


# pooling layer
Set the values to `strides` and `ksize` such that
the output shape after pooling is (1, 2, 2, 1).

In [17]:
def maxpool(input):
    # TODO: Set the ksize (filter size) for each dimension (batch_size, height, width, depth)
    ksize = [1, 2, 2, 1]
    # TODO: Set the stride for each dimension (batch_size, height, width, depth)
    strides = [1, 2, 2, 1]
    # TODO: set the padding, either 'VALID' or 'SAME'.
    padding = 'VALID'
    return tf.nn.max_pool(input, ksize, strides, padding)
    
pool_layer = maxpool(X)
with tf.Session() as sess:
    sess.run(tf. global_variables_initializer())
    pool_out = sess.run(pool_layer)
print(pool_out.shape)
print(pool_out)

(1, 2, 2, 1)
[[[[  2.5]
   [ 10. ]]

  [[ 15. ]
   [  6. ]]]]
