# softmax equation:
$$ S(y_{ij}) = \frac{e^{y_{ij}}}{\sum_j{e^{y_{ij}}}}$$  
The probabilities for each column must sum to 1

In [9]:
import numpy as np

def my_softmax(X):
    exp = np.exp(X)
    return exp / np.sum(exp, axis=0)

def softmax(X):
    # why X - np.max(X)
    # 当编写计算Softmax函数的代码时，由于指数的原因，中间项可能会非常大。
    # 大数分割可能在数值上不稳定，因此使用规范化技巧很重要
    exp = np.exp(X - np.max(X))
    return exp / exp.sum(axis=0)

logits1 = [3.0, 1.0, 0.2]
logits2 = np.array([
    [1, 2, 3, 6],
    [2, 4, 5, 6],
    [3, 8, 7, 6]])
print(softmax(logits2))

[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]


In [16]:
# softmax function in tensorflow
import tensorflow as tf

logits = tf.placeholder(tf.float32)
tf_softmax = tf.nn.softmax(logits)
with tf.Session() as sess:
    print(sess.run(tf_softmax, feed_dict={logits: logits1})) 

[ 0.83601874  0.11314283  0.05083835]
