In [2]:
import numpy as np
import tensorflow as tf

# softmax equation:
$$ S(y_{ij}) = \frac{e^{y_{ij}}}{\sum_j{e^{y_{ij}}}}$$  
The probabilities for each column must sum to 1

In [15]:
def my_softmax(X):
    exp = np.exp(X)
    return exp / np.sum(exp, axis=0)

def softmax(X):
    # why X - np.max(X)
    # 当编写计算Softmax函数的代码时，由于指数的原因，中间项可能会非常大。
    # 大数分割可能在数值上不稳定，因此使用规范化技巧很重要
    exp = np.exp(X - np.max(X))
    return exp / exp.sum(axis=0)

logits1 = np.array([3.0, 1.0, 0.2])
logits2 = np.array([
    [1, 2, 3, 6],
    [2, 4, 5, 6],
    [3, 8, 7, 6]])
print(softmax(logits2))

[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]


In [16]:
# softmax function in tensorflow
tf.multiply
logits = tf.placeholder(tf.float32)
# logits = tf.multiply(tf.placeholder(tf.float32), 10)
# logits = tf.divide(tf.placeholder(tf.float32), 10)

logits1 = logits1 / 10

tf_softmax = tf.nn.softmax(logits)
with tf.Session() as sess:
    print(sess.run(tf_softmax, feed_dict={logits: logits1})) 

[ 0.38842273  0.31801364  0.29356357]


# cross entropy
$$ D(\overline{y}, y) = - \sum_j{y_jln\overline{y_j}}$$

In [4]:
x = tf.reduce_sum([1,2,3,4,5])
y = tf.log([10.0, 9.0])
with tf.Session() as sess:
    print sess.run(x)
    print sess.run(y)

15
[ 2.30258512  2.19722462]


In [3]:
softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

with tf.Session() as sess:
    print sess.run(cross_entropy, feed_dict={one_hot: one_hot_data, softmax: softmax_data})

0.356675


# numerical stability
big number and small number

In [6]:
a = 1000000000
for i in range(1000000):
    a += 1e-6
print a - 1000000000
print 1e+0

0.953674316406
1.0
