# save and load model

## saving variables

In [21]:
import tensorflow as tf

# The file path to save the data
save_file = './model.ckpt'

# Two tensor variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))
                   
# Class used to save and/or restore tensor variables
saver = tf.train.Saver()

In [22]:
with tf.Session() as sess:
    # Initialize all the variables
    sess.run(tf.global_variables_initializer())
    
    # Show the values of weights and bias
    print(sess.run(weights))
    print(sess.run(bias))
    
    # Save the model
    saver.save(sess, save_file)

[[-1.14969206 -1.58869731  0.79880112]
 [-0.46565694  0.00359792  0.09856119]]
[-1.03672671  1.53040361 -0.22871782]


## Loading variables

In [16]:
# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

In [20]:
with tf.Session() as sess:
    # Load the weights and bias
    saver.restore(sess, save_file)

    # Show the values of weights and bias
    print(sess.run(weights))
    print(sess.run(bias))

[[ 0.19999918 -1.30922127  1.04423773]
 [ 0.84673315  0.66303104  0.55323392]]
[-0.90264946 -0.852772   -0.55931145]
