# save and load model

## saving variables

In [21]:
import tensorflow as tf

# The file path to save the data
save_file = './model.ckpt'

# Two tensor variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))
                   
# Class used to save and/or restore tensor variables
saver = tf.train.Saver()

In [25]:
with tf.Session() as sess:
    # Initialize all the variables
    sess.run(tf.global_variables_initializer())
    
    # Show the values of weights and bias
    print(sess.run(weights))
    print(sess.run(bias))
    
    # Save the model
    saver.save(sess, save_file)

[[-0.43587166  0.30384061 -0.30265552]
 [ 0.20184377 -0.70636874 -0.06085921]]
[-0.74222773  0.65368062 -0.67239714]


## Loading variables

In [23]:
# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

In [28]:
with tf.Session() as sess:
    # Load the weights and bias
    saver.restore(sess, save_file)

    # Show the values of weights and bias
    print(sess.run(weights))
    print(sess.run(bias))

[[-0.43587166  0.30384061 -0.30265552]
 [ 0.20184377 -0.70636874 -0.06085921]]
[-0.74222773  0.65368062 -0.67239714]
